### ISSUE TITLE
Enable `always-multiline` option for `@typescript-eslint/comma-dangle` for better DX

### ISSUE THREAD

**Issue by NozomuIkuta** [globalbrain/eslint-config#9]
Currently, `@globalbrain/eslint-config` disallows trailing commas in source code in any cases.

```typescript
// NG
const array1 = [1,2,3,]
const array2 = [
  1,
  2,
  3,
]
```

With this setting, it's hard to replace strings in multi-lined array/object with multi-cursor because the cursor on the last element always differ from the others by 1 character (see below, `|` are cursors).

```typescript
const array2 = [
  1,|
  2,|
  3|
]
```

If Move cursors to the right to replace characters...

```typescript
const array2 = [
  1|,
  2|,
  |3
]
```

It's common to replace some parts of words (e.g. change snake_case to camelCase, etc.) at once. So, IMO, it's convenient to enable `always-multiline` option so that trailing commas only in multi-lined array/object are allowed (actually, `@antfu/eslint-config` enable it). Migration from "never trailing commas" to "always-multiline" is not hard just because it's auto-fixable.

**Comment by kiaking** [comment]
No, I don't think this is a good idea.

I do understand and feel your proposal. For example, PHP rule is to have comma dangle. And I do understand the every benefit it has.

However, this is very tiny subjective matter where it reads to holy war.

For example, same thing could be said to trailing semicolon. One could argue to say that it prevents some edge cases and eslint would fix it automatically so we should add semicolon. These are really just a preference, and the whole point of having shared esling-config like this is to eliminate those subjective discussion.

As a rule of thumb, We should strive to match the styling to Vue's common styles as much as possible because we do work with Vue related stuff often.

So, if most of the Vue code base applies comma dangle, I would be more than happy to apply this rule, but for now, let's keep it as is 👍

**Comment by NozomuIkuta** [comment]
If it's Vue community's preference at the moment, I will follow it.
Thank you for explanation. 🙋
